name = "QuantumStatePlots"
uuid = "42a22799-231f-43e2-8d9d-80a724399a88"
authors = ["JingYu Ning <foldfelis@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumStateBase = "73ce9c4f-35d1-4161-b9e6-26915895bfed"

[compat]
Plots = "1"
QuantumStateBase = "0.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
